name: Push Docker Image

on:
  push:
    branches: [ master ]
env:
  ACR_HOST: ${{secrets.ACR_HOST}}
  ACR_USER: ${{secrets.ACR_USER}}
  ACR_PASS: ${{secrets.ACR_PASS}}
  IMAGE_TAG: ${{env.ACR_HOST}}:lazaromenezes/generatedata:$(date +%s)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build --file Dockerfile --tag ${{env.IMAGE_TAG}} .
    - name: Push to Azure ACR
      run: |
        echo ${{env.ACR_PASS}} | docker login -u ${{env.ACR_USER}} --password-stdin ${{env.ACR_HOST}}
        docker push ${{env.IMAGE_TAG}}
        
    
      

    
    
