name: Push Docker Image

on:
  push:
    branches: [ master ]
env:
  ACR_HOST: ${{secrets.ACR_HOST}}
  ACR_USER: ${{secrets.ACR_USER}}
  ACR_PASS: ${{secrets.ACR_PASS}}
  LATEST_TAG: ${{env.ACR_HOST}}/generatedata:latest

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      id: build
      run: | 
        VERSION_TAG=${{env.ACR_HOST}}/generatedata:$(date +%s)

        docker build --file Dockerfile --tag $VERSION_TAG --tag ${{env.LATERST_TAG}}.
    - name: Push to Azure ACR
      run: |
        echo ${{env.ACR_PASS}} | docker login -u ${{env.ACR_USER}} --password-stdin ${{env.ACR_HOST}}
        docker push ${{env.LATEST_TAG}}
        
